---

- name: NODEJS | CHECK IF NODE IS INSTALLED
  shell: node -v
  register: node_check
  ignore_errors: true

- set_fact:
    arch: "{{ (ansible_architecture == 'x86_64') | ternary('x64', 'x86')}}"

- name: NODEJS | DOWNLOAD
  get_url: dest=/opt/node.tar.gz url=http://nodejs.org/dist/{{ version }}/node-{{ version }}-linux-{{ arch }}.tar.gz
  when: node_check|failed

- name: NODEJS | UNPACK
  unarchive: src=/opt/node.tar.gz dest=/opt copy=no
  when: node_check|failed

- name: NODEJS | LINK BINARIES
  file: dest="/usr/bin/{{ item}}" src="/opt/node-{{ version }}-linux-{{ arch }}/bin/{{ item }}" state=link
  when: node_check|failed
  with_items:
   - npm
   - node

- name: NODEJS | INSTALL PACKAGES
  npm: name={{ item }} global=yes state=present
  with_items: "{{ install }}"
